kind: ConfigMap
apiVersion: v1
metadata: 
  name: nginx-conf
data: 
  nginx.prod.conf: |
    events {
      worker_connections 4096;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      server {
        listen 80 default_server;
        server_name localhost 127.0.0.1;
        index index.html;
        location / {
          root /usr/share/nginx/html;
          try_files $uri $uri/ /index.html;
        }

        location /articles {
          proxy_pass http://api;
        }
      }
    }