apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-deployment
spec:
  selector:
    matchLabels:
      app: www
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        image: www:212c8415f843d97ff8e5b3218bd2a3190546a2d0f554aedad4b305cee177cf38
        imagePullPolicy: IfNotPresent 
        volumeMounts: 
        - name: nginx-conf 
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.prod.conf 
        ports:
        - containerPort: 3000
      volumes: 
      - name: nginx-conf
        configMap: 
          name: nginx-conf
