apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-deployment
spec:
  selector:
    matchLabels:
      app: www
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        image: www:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
